---- RESOURCES ----
CREATE SEQUENCE RES_SEQ CACHE 1000;

CREATE MEMORY TABLE RES(
  ID                  INTEGER(9)     PRIMARY KEY HASH
 ,URI                 VARCHAR(250)   NOT NULL
 ,OBSOLETE            BOOLEAN
 ,EXTERNAL            BOOLEAN
);
CREATE UNIQUE HASH INDEX IDX_RES_URI ON RES(URI);

CREATE TABLE RES_NAMES(
  RES_ID              INTEGER(9)     NOT NULL
 ,IMPORTED_NAME       VARCHAR(200)   NOT NULL
 ,LOWER_IMPORTED_NAME VARCHAR(200)   AS LOWER(IMPORTED_NAME)
);
CREATE INDEX IDX_RES_NAMES_RES ON RES_NAMES(RES_ID);
CREATE INDEX IDX_RES_NAMES_IMPORTED_NAME ON RES_NAMES(LOWER_IMPORTED_NAME, RES_ID);

---- OBJECTS ----
CREATE TABLE OBJ(
  RES_ID              INTEGER(9)     NOT NULL
 ,FRAG                VARCHAR(250)   NOT NULL
 ,NAME                VARCHAR(200)
 ,ECLASS_ID           INTEGER(9)     NOT NULL
 ,USER_DATA           ARRAY
);
CREATE INDEX IDX_OBJ_RES_FRAG ON OBJ(RES_ID, FRAG);
CREATE INDEX IDX_OBJ_ECLASS ON OBJ(ECLASS_ID);

---- REFERENCES ----
CREATE TABLE REF(
  RES_ID              INTEGER(9)     NOT NULL
 ,SRC_FRAG            VARCHAR(2500)  NOT NULL   -- TODO LOWER THIS LIMIT
 ,CONT_FRAG           VARCHAR(250)
 ,TGT_RES_ID          INTEGER(9)
 ,TGT_FRAG            VARCHAR(250)
 ,EREF_ID             INTEGER(9)
 ,IDX                 INTEGER(9)
);
CREATE INDEX IDX_REF_RES ON REF(RES_ID);
CREATE INDEX IDX_REF_TGT ON REF(TGT_RES_ID, TGT_FRAG);

---- ECLASSES ----
CREATE SEQUENCE ECLASS_SEQ;

CREATE MEMORY TABLE ECLASS(
  ID                  INTEGER(9)     PRIMARY KEY
 ,URI                 VARCHAR(200)   NOT NULL
);
CREATE UNIQUE HASH INDEX IDX_ECLASS_URI ON ECLASS(URI);

CREATE MEMORY TABLE ECLASS_SUPERTYPES(
  ECLASS_ID           INTEGER(9)     NOT NULL
 ,SUPERTYPE_ECLASS_ID INTEGER(9)     NOT NULL
);
CREATE INDEX IDX_ECLASS_SUBTYPES ON ECLASS_SUPERTYPES(SUPERTYPE_ECLASS_ID, ECLASS_ID);

---- EREFERENCES ----
CREATE SEQUENCE EREF_SEQ;

CREATE MEMORY TABLE EREF(
  ID                  INTEGER(9)     PRIMARY KEY
 ,URI                 VARCHAR(200)   NOT NULL
);
