---- RESOURCE MAP ----
CREATE MEMORY TABLE RES_MAP(
  RES_ID              INT       PRIMARY KEY HASH
);

CREATE MEMORY TABLE OLD_RES_MAP(
  RES_ID              INT       PRIMARY KEY HASH
);

CREATE MEMORY TABLE WORK_SET(
  ID                  INT       PRIMARY KEY HASH
) NOT PERSISTENT;

---- RESOURCES ----
CREATE SEQUENCE RES_SEQ CACHE 100;

CREATE MEMORY TABLE RES(
  ID                  INT       PRIMARY KEY HASH
 ,URI                 VARCHAR   NOT NULL
 ,EXTERNAL            BOOLEAN
);
CREATE HASH INDEX IDX_RES_URI ON RES(URI);

CREATE TABLE RES_NAMES(
  RES_ID              INT       NOT NULL
 ,IMPORTED_NAME       VARCHAR   NOT NULL
 ,LOWER_IMPORTED_NAME VARCHAR   AS LOWER(IMPORTED_NAME)
);
CREATE INDEX IDX_RES_NAMES_RES ON RES_NAMES(RES_ID);
CREATE INDEX IDX_RES_NAMES_IMPORTED_NAME ON RES_NAMES(LOWER_IMPORTED_NAME, RES_ID);

---- OBJECTS ----
CREATE TABLE OBJ(
  RES_ID              INT       NOT NULL
 ,SEQ_NR              INT       NOT NULL
 ,FRAG                VARCHAR   NOT NULL
 ,NAME                VARCHAR
 ,ECLASS_ID           INT       NOT NULL
 ,USER_DATA           ARRAY
);
CREATE INDEX IDX_OBJ_RES_FRAG ON OBJ(RES_ID, FRAG);
-- TODO CHECK IF IDX_OBJ_RES_SEQ_NR IS REQUIRED
CREATE INDEX IDX_OBJ_RES_SEQ_NR ON OBJ(RES_ID, SEQ_NR);
CREATE INDEX IDX_OBJ_ECLASS ON OBJ(ECLASS_ID);

---- REFERENCES ----
CREATE TABLE REF(
  RES_ID              INT       NOT NULL
 ,SRC_FRAG            VARCHAR   NOT NULL
 ,CONT_FRAG           VARCHAR
 ,TGT_RES_ID          INT
 ,TGT_FRAG            VARCHAR
 ,EREF_ID             INT
 ,IDX                 INT
);
CREATE INDEX IDX_REF_RES ON REF(RES_ID);
CREATE INDEX IDX_REF_TGT ON REF(TGT_RES_ID, TGT_FRAG);

---- ECLASSES ----
CREATE SEQUENCE ECLASS_SEQ;

CREATE MEMORY TABLE ECLASS(
  ID                  INT       PRIMARY KEY
 ,URI                 VARCHAR   NOT NULL
);
CREATE UNIQUE HASH INDEX IDX_ECLASS_URI ON ECLASS(URI);

CREATE MEMORY TABLE ECLASS_SUPERTYPES(
  ECLASS_ID           INT       NOT NULL
 ,SUPERTYPE_ECLASS_ID INT       NOT NULL
);
CREATE INDEX IDX_ECLASS_SUBTYPES ON ECLASS_SUPERTYPES(SUPERTYPE_ECLASS_ID, ECLASS_ID);

---- EREFERENCES ----
CREATE SEQUENCE EREF_SEQ;

CREATE MEMORY TABLE EREF(
  ID                  INT       PRIMARY KEY
 ,URI                 VARCHAR   NOT NULL
);
