---- RESOURCE MAP ----
CREATE MEMORY TABLE RES_MAP(
  RES_ID              INTEGER   PRIMARY KEY HASH
);

CREATE MEMORY TABLE OLD_RES_MAP(
  RES_ID              INTEGER   PRIMARY KEY HASH
);

---- RESOURCES ----
CREATE SEQUENCE RES_SEQ CACHE 100;

CREATE MEMORY TABLE RES(
  ID                  INTEGER   PRIMARY KEY HASH
 ,URI                 VARCHAR   NOT NULL
 ,EXTERNAL            BOOLEAN
);
CREATE HASH INDEX IDX_RES_URI ON RES(URI);

CREATE TABLE RES_NAMES(
  RES_ID              INTEGER   NOT NULL
 ,IMPORTED_NAME       VARCHAR   NOT NULL
 ,LOWER_IMPORTED_NAME VARCHAR   AS LOWER(IMPORTED_NAME)
);
CREATE INDEX IDX_RES_NAMES_RES ON RES_NAMES(RES_ID);
CREATE INDEX IDX_RES_NAMES_IMPORTED_NAME ON RES_NAMES(LOWER_IMPORTED_NAME, RES_ID);

---- OBJECTS ----
CREATE TABLE OBJ(
  RES_ID              INTEGER   NOT NULL
 ,FRAG                VARCHAR   NOT NULL
 ,NAME                VARCHAR
 ,ECLASS_ID           INTEGER   NOT NULL
 ,USER_DATA           ARRAY
);
CREATE INDEX IDX_OBJ_RES_FRAG ON OBJ(RES_ID, FRAG);
CREATE INDEX IDX_OBJ_ECLASS ON OBJ(ECLASS_ID);

---- REFERENCES ----
CREATE TABLE REF(
  RES_ID              INTEGER   NOT NULL
 ,SRC_FRAG            VARCHAR   NOT NULL
 ,CONT_FRAG           VARCHAR
 ,TGT_RES_ID          INTEGER
 ,TGT_FRAG            VARCHAR
 ,EREF_ID             INTEGER
 ,IDX                 INTEGER
);
CREATE INDEX IDX_REF_RES ON REF(RES_ID);
CREATE INDEX IDX_REF_TGT ON REF(TGT_RES_ID, TGT_FRAG);

---- ECLASSES ----
CREATE SEQUENCE ECLASS_SEQ;

CREATE MEMORY TABLE ECLASS(
  ID                  INTEGER   PRIMARY KEY
 ,URI                 VARCHAR   NOT NULL
);
CREATE UNIQUE HASH INDEX IDX_ECLASS_URI ON ECLASS(URI);

CREATE MEMORY TABLE ECLASS_SUPERTYPES(
  ECLASS_ID           INTEGER   NOT NULL
 ,SUPERTYPE_ECLASS_ID INTEGER   NOT NULL
);
CREATE INDEX IDX_ECLASS_SUBTYPES ON ECLASS_SUPERTYPES(SUPERTYPE_ECLASS_ID, ECLASS_ID);

---- EREFERENCES ----
CREATE SEQUENCE EREF_SEQ;

CREATE MEMORY TABLE EREF(
  ID                  INTEGER   PRIMARY KEY
 ,URI                 VARCHAR   NOT NULL
);
